### ISSUE TITLE
pivotal intellij keymaps don't work

### ISSUE THREAD

**Issue by atomanyih** [pivotal/pivotal_ide_prefs#49] opened 2016-12-05 18:54 UTC
on 2016.3

Pivotal IntelliJ is blank
![screen shot 2016-12-05 at 10 52 51 am](https://cloud.githubusercontent.com/assets/2305345/20897897/160b2498-bad9-11e6-892e-61bd6e3c8d50.png)

but Pivotal Common works fine
![screen shot 2016-12-05 at 10 52 56 am](https://cloud.githubusercontent.com/assets/2305345/20897903/171707da-bad9-11e6-960d-090fd4c8eabc.png)

**Comment by gp-workload-manager** [comment] 2016-12-08 22:40
See Issue #48

**Comment by moonmaster9000** [comment] 2017-01-27 18:54
Hi All, 

Closing this as duplicate of #48. See #48 for resolution.

**Closed by moonmaster9000** 2017-01-27 18:54 UTC
